SELECT "Adding triggers to reqn table" AS "";

DELIMITER $$

DROP TRIGGER IF EXISTS reqn_AFTER_INSERT $$
CREATE DEFINER = CURRENT_USER TRIGGER reqn_AFTER_INSERT AFTER INSERT ON reqn FOR EACH ROW
BEGIN
  CALL update_reqn_last_ethics_approval( NEW.id );
END$$

DELIMITER ;
