SELECT "Creating new data_option_subcategory table" AS "";

CREATE TABLE IF NOT EXISTS data_option_subcategory (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL,
  create_timestamp TIMESTAMP NOT NULL,
  type ENUM("baseline", "mcq", "physical", "biomarker") NOT NULL,
  rank INT UNSIGNED NOT NULL,
  data_option_parent_id INT UNSIGNED NULL,
  code VARCHAR(127) NOT NULL,
  name_en VARCHAR(127) NOT NULL,
  name_fr VARCHAR(127) NOT NULL,
  note_en VARCHAR(1023) NULL,
  note_fr VARCHAR(1023) NULL,
  PRIMARY KEY (id),
  INDEX fk_data_option_parent_id (data_option_parent_id ASC),
  UNIQUE INDEX uq_type_rank (type ASC, rank ASC),
  UNIQUE INDEX uq_code (code ASC),
  CONSTRAINT fk_data_option_subcategory_data_option_parent_id
    FOREIGN KEY (data_option_parent_id)
    REFERENCES data_option_parent (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT IGNORE INTO data_option_subcategory( type, rank, data_option_parent_id, code, name_en, name_fr, note_en, note_fr ) VALUES
( "baseline", 1, NULL, "age", "Age (AGE)", "Âge (AGE)", NULL, NULL ),
( "baseline", 2, NULL, "sex", "Sex (SEX)", "Sexe (SEX)", NULL, NULL ),
( "baseline", 3, 1, "country_of_birth", "Country of birth", "Pays de naissance", NULL, NULL ),
( "baseline", 4, 1, "province_of_residence", "Province of residence", "Province de résidence", NULL, NULL ),
( "baseline", 5, 1, "urban_rural_classification", "Urban / Rural Classification", "Classement des zones urbaines / rurales", "Determined using the Postal Code Conversion File (PCCF) from Statistics Canada.", "Déterminé à l’aide du Fichier de conversion des codes postaux (FCCP) de Statistique Canada." ),
( "baseline", 6, 1, "census_subdivision_codes_and_names", "Census Subdivision (Codes and Names)", "Subdivisions de recensement (Codes et noms)", "Determined using the Postal Code Conversion File (PCCF) from Statistics Canada.  Adequate justification must be provided within the project description (Application Part 1) to justify the request of these data.", "Déterminé à l’aide du Fichier de conversion des codes postaux (FCCP) de Statistique Canada.  Lorsque vous demandez ces données, veuillez inclure u ne justification adéquate dans la description du projet (Part ie 1 de la demande)." ),
( "baseline", 7, 1, "forward_sortation_area", "Forward Sortation Area", "Zones de tri d’acheminemen", "Determined using the Postal Code Conversion File (PCCF) from Statistics Canada.  Adequate justification must be provided within the project description (Application Part 1) to justify the request of these data.", "Déterminé à l’aide du Fichier de conversion des codes postaux (FCCP) de Statistique Canada.  Lorsque vous demandez ces données, veuillez inclure u ne justification adéquate dans la description du projet (Part ie 1 de la demande)." ),
( "baseline", 8, 1, "ethnicity", "Ethnicity", "Ethnicité", NULL, NULL ),
( "baseline", 9, 1, "culture", "Culture", "Culture", NULL, NULL ),
( "baseline", 10, 1, "language", "Language", "Langue", NULL, NULL ),
( "baseline", 11, 1, "religion", "Religion", "Religion", NULL, NULL ),
( "baseline", 12, 1, "marital_status", "Marital status", "État matrimonial", NULL, NULL ),
( "baseline", 13, 1, "sexual_orientation", "Sexual orientation", "Orientation sexuelle", NULL, NULL ),
( "baseline", 14, NULL, "home_ownership", "Home Ownership (OWN)", "Propriétaires (OWN)", NULL, NULL ),
( "baseline", 15, NULL, "education", "Education (ED)", "Éducation (ED)", NULL, NULL ),
( "baseline", 16, NULL, "veteran_identifiers", "Veteran Identifiers (VET)", "Anciens combattants (VET)", NULL, NULL ),
( "baseline", 17, NULL, "height_and_weight", "Height and Weight (HWT)", "Taille et poids (HWT)", NULL, NULL ),
( "baseline", 18, NULL, "smoking", "Smoking (SMK)", "Consommation de tabac (SMK)", NULL, NULL ),
( "baseline", 19, NULL, "alcohol_use", "Alcohol Use (ALC)", "Consommation d’alcool (ALC)", NULL, NULL ),
( "baseline", 20, NULL, "general_health", "General Health (GEN)", "État général de santé (GEN)", NULL, NULL ),
( "baseline", 21, NULL, "general_health_open_text_question", "General Health - open text question (qualitative)", "État général de santé - question ouverte (qualitative)", NULL, NULL ),
( "baseline", 22, NULL, "nutrition_short_diet_questionnaire", "Nutrition: Short Diet Questionnaire (NUT)", "Nutrition : Questionnaire court sur le régime alimentaire (NUT)", NULL, NULL ),
( "baseline", 23, NULL, "womens_health", "Women’s Health (WHO)", "Santé des femmes (WHO)", NULL, NULL ),
( "baseline", 24, NULL, "vision1", "Vision (VIS)", "Vision (VIS)", NULL, NULL ),
( "baseline", 25, NULL, "hearing1", "Hearing (HRG)", "Audition (HRG)", NULL, NULL ),
( "baseline", 26, 2, "osteoarthritis_or_arthritis_knee", "Osteoarthritis or arthritis - Knee", "Arthrose ou arthrite - Genou", NULL, NULL ),
( "baseline", 27, 2, "osteoarthritis_or_arthritis_hip", "Osteoarthritis or arthritis - Hip", "Arthrose ou arthrite - Hanche", NULL, NULL ),
( "baseline", 28, 2, "osteoarthritis_or_arthritis_hands", "Osteoarthritis or arthritis - Hand(s)", "Arthrose ou arthrite - Main(s)", NULL, NULL ),
( "baseline", 29, 2, "rheumatoid_arthritis", "Rheumatoid arthritis", "Polyarthrite rhumatoïde", NULL, NULL ),
( "baseline", 30, 2, "other_arthritis", "Other arthritis", "Autres forms d’arthrite", NULL, NULL ),
( "baseline", 31, 2, "respiratory_asthma", "Respiratory - Asthma", "Respiratoire - Asthme", NULL, NULL ),
( "baseline", 32, 2, "respiratory_copd", "Respiratory - COPD", "Respiratoire - MPOC", NULL, NULL ),
( "baseline", 33, 2, "cardiovascular_high_blood_pressure", "Cardiovascular - High blood pressure", "Cardiovasculaire - Hypertension", NULL, NULL ),
( "baseline", 34, 2, "cardiovascular_diabetes", "Cardiovascular - Diabetes", "Cardiovasculaire - Diabète", NULL, NULL ),
( "baseline", 35, 2, "cardiovascular_heart_disease", "Cardiovascular - Heart disease", "Cardiovasculaire - Maladie cardiaque", NULL, NULL ),
( "baseline", 36, 2, "cardiovascular_peripheral_vascular_disease", "Cardiovascular - Peripheral Vascular Disease", "Cardiovasculaire - Maladie vasculaire périphérique", NULL, NULL ),
( "baseline", 37, 2, "stroke", "Stroke", "AVC", NULL, NULL ),
( "baseline", 38, 2, "neurological", "Neurological", "Neurologique", NULL, NULL ),
( "baseline", 39, 2, "gastrointestinal", "Gastrointestinal", "Gastrointestinal", NULL, NULL ),
( "baseline", 40, 2, "vision2", "Vision", "Vision", NULL, NULL ),
( "baseline", 41, 2, "cancer", "Cancer", "Cancer", NULL, NULL ),
( "baseline", 42, 2, "mental_health", "Mental Health", "Santé mentale", NULL, NULL ),
( "baseline", 43, 2, "other_conditions", "Other Conditions", "Autres maladies", NULL, NULL ),
( "baseline", 44, 2, "infections", "Infections", "Infections", NULL, NULL ),
( "baseline", 45, NULL, "medications", "Medications (MEDI)", "Médicaments (MEDI)", NULL, NULL ),
( "baseline", 46, NULL, "functional_status", "Functional Status (FUL)", "Capacités fonctionnelles (FUL)", "For 135 participants, the baseline DCS visit was completed by phone for various reasons including time constraints for recruitment fulfillment toward the end of Baseline data collection and some cases where the participants were unable to physically present at the DCS but wished to remain part of CLSA. For 2 participants, the Baseline DCS site visit was completed in person at the participant’s residence as a pilot for the DCS at home.", "Pour 135 participants, la visite initiale au Site de collecte de données a été réalisée par téléphone pour diverses raisons, y compris des contraintes de temps liées au recrutement vers la fin de la collecte des données de départ ou des participants ne pouvant pas se présenter physiquement au site, mais souhaitant faire partie de l’ÉLCV. Pour 2 participants, la visite initiale au Site de collecte de données a été faite en personne à leur résidence dans le cadre de l’étude pilote de l’entrevue du site réalisée à la maison." ),
( "baseline", 47, NULL, "life_space_index", "Life Space Index (LSI)", "Évaluation de l’aire de mobilité (LSI)", NULL, NULL ),
( "baseline", 48, NULL, "sleep", "Sleep (SLE)", "Sommeil (SLE)", NULL, NULL ),
( "baseline", 49, NULL, "basic_activities_of_daily_living", "Basic Activities of Daily Living (ADL)", "Activités de base de la vie quotidienne (ADL)", NULL, NULL ),
( "baseline", 50, NULL, "instrumental_activities_of_daily_living", "Instrumental Activities of Daily Living (IAL)", "Activités instrumentals de la vie quotidienne (IAL)", NULL, NULL ),
( "baseline", 51, 3, "reyi", "REYI", "REYI", NULL, NULL ),
( "baseline", 52, 3, "animal_fluency_test", "Animal Fluency Test", "Test de fluence (animaux)", NULL, NULL ),
( "baseline", 53, 3, "mental_alternation_test", "Mental Alternation Test", "Test d’alternance mentale", NULL, NULL ),
( "baseline", 54, 3, "reyii", "REYII", "REYII", NULL, NULL ),
( "baseline", 55, 4, "timebased", "Time-Based (TMT)", "En fonction du temps (TMT)", NULL, NULL ),
( "baseline", 56, 4, "eventbased", "Event-Based (PMT)", "En fonction d’un événement (PMT)", NULL, NULL ),
( "baseline", 57, NULL, "stroop_victoria_version", "Stroop - Victoria Version (STP)", "Stroop - version de Victoria (STP)", NULL, NULL ),
( "baseline", 58, NULL, "controlled_oral_word_association", "Controlled Oral Word Association (FAS)", "Test oral contrôlé d’association de mots (FAS)", NULL, NULL ),
( "baseline", 59, NULL, "choice_reaction_time", "Choice Reaction Time (CRT)", "Test de temps de réaction (CRT)", NULL, NULL ),
( "baseline", 60, NULL, "depression", "Depression (DEP)", "Dépression (DEP)", NULL, NULL ),
( "baseline", 61, NULL, "satisfaction_with_life", "Satisfaction with Life (SLS)", "Satisfaction à l’égard de la vie (SLS)", NULL, NULL ),
( "baseline", 62, NULL, "posttraumatic_stress_disorder", "Posttraumatic Stress Disorder (PSD)", "Trouble de stress post-traumatique (PSD)", NULL, NULL ),
( "baseline", 63, NULL, "social_networks", "Social Networks (SN)", "Réseaux sociaux (SN)", NULL, NULL ),
( "baseline", 64, NULL, "social_support_availability", "Social Support - Availability (SSA)", "Soutien social - Disponibilité (SSA)", NULL, NULL ),
( "baseline", 65, NULL, "social_participation", "Social Participation (SPA)", "Participation sociale (SPA)", NULL, NULL ),
( "baseline", 66, NULL, "care_receiving_formal_care", "Care Receiving 1 / Formal Care (CR1)", "Soins reçus 1 / Soins à domicile (CR1)", NULL, NULL ),
( "baseline", 67, NULL, "care_receiving_informal_care", "Care Receiving 2 / Informal Care (CR2)", "Soins reçus 2 / Autres types de soins (CR2)", NULL, NULL ),
( "baseline", 68, NULL, "care_giving", "Care Giving (CAG)", "Prestation de soins (CAG)", NULL, NULL ),
( "baseline", 69, NULL, "injuries", "Injuries (INJ)", "Blessures (INJ)", NULL, NULL ),
( "baseline", 70, NULL, "falls_and_consumer_products", "Falls and Consumer Products (FAL)", "Chutes et produits de consommation (FAL)", NULL, NULL ),
( "baseline", 71, NULL, "retirement_status", "Retirement Status (RET)", "Retraite (RET)", NULL, NULL ),
( "baseline", 72, NULL, "preretirement_labour_force_participation", "Pre-Retirement Labour Force Participation (LFP)", "Participation à la population active avant la retraite (LFP)", NULL, NULL ),
( "baseline", 73, NULL, "preretirement_labour_force_participation_open_text_question", "Pre-Retirement Labour Force Participation - open text question", "Participation à la population active avant la retraite - question ouverte", "Open text data for occupation and industry are available. These data are not coded. Any coding of the released open text data has to be a coordinated effort between the Approved User and the CLSA. Please contact us for details access@clsa-elcv.ca", "Des données ouvertes pour la profession et l’industrie sont disponibles. Ces données ne sont pas codées.  Toute codification de données ouvertes diffusées doit être coordonnée entre l’utilisateur autorisé et l’ÉLCV.  Pour plus d’information, contactez-nous à access@clsa-elcv.ca" ),
( "baseline", 74, NULL, "labour_force", "Labour Force (LBF)", "Population active (LBF)", NULL, NULL ),
( "baseline", 75, NULL, "labour_force_open_text_question", "Labour Force - open text question", "Population active - question ouverte", "Open text data for occupation and industry are available. These data are not coded. Any coding of the released open text data has to be a coordinated effort between the Approved User and the CLSA. Please contact us for details access@clsa-elcv.ca", "Des données ouvertes pour la profession et l’industrie sont disponibles. Ces données ne sont pas codées.  Toute codification de données ouvertes diffusées doit être coordonnée entre l’utilisateur autorisé et l’ÉLCV.  Pour plus d’information, contactez-nous à access@clsa-elcv.ca" ),
( "baseline", 76, NULL, "retirement_planning", "Retirement Planning (RPL)", "Planification de la retraite (RPL)", NULL, NULL ),
( "baseline", 77, NULL, "income", "Income (INC)", "Revenu (INC)", NULL, NULL ),
( "baseline", 78, 5, "diabetes", "Diabetes (DIA)", "Diabète (DIA)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 79, 5, "strokecerebrovascular_event", "Stroke/Cerebrovascular Event (STR)", "AVC (STR)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 80, 5, "traumatic_brain_injury", "Traumatic Brain Injury (TBI)", "Traumatisme crânien (TBI)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 81, 5, "hypo_and_hyperthyroidism", "Hypo and Hyperthyroidism (HYP)", "Hypo-et hyperthyroïdie (HYP)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 82, 5, "hypertension", "Hypertension (HBP)", "Hypertension (HBP)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 83, 5, "ischemic_heart_disease", "Ischemic Heart Disease (IHD)", "Cardiopathie ischémique (IHD)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 84, 5, "who_rose_questionnaire", "WHO Rose Questionnaire (ROS)", "Questionnaire Rose de l’OMS (ROS)", NULL, NULL ),
( "baseline", 85, 5, "osteoarthritis_of_the_hand", "Osteoarthritis of the Hand (OSA)", "Arthrose de la main (OSA)", NULL, NULL ),
( "baseline", 86, 5, "osteoarthritis_of_the_hip", "Osteoarthritis of the Hip (OSH)", "Arthrose de la hanche (OSH)", NULL, NULL ),
( "baseline", 87, 5, "osteoarthritis_of_the_knee", "Osteoarthritis of the Knee (OSK)", "Arthrose du genou (OSK)", NULL, NULL ),
( "baseline", 88, 5, "musculoskeletal_other", "Musculoskeletal: Other (OAR)", "Musculosquelettique : autre (OAR)", NULL, NULL ),
( "baseline", 89, 5, "osteoporosis", "Osteoporosis (OST)", "Ostéoporose (OST)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 90, 5, "neuropsychiatric", "Neuro-psychiatric (DPR)", "Neuropsychiatrique (DPR)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 91, 5, "parkinsonism1", "Parkinsonism (PKD)", "Parkinsonisme (PKD)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "baseline", 92, 5, "chronic_airflow_obstruction", "Chronic Airflow Obstruction (CAO)", "Obstruction chronique des voies respiratoires (CAO)", "Open text data under review - in preparation for future release. (Please see Variables under review)", "Les données ouvertes sont en cours d’examen – en préparation pour une diffusion ultérieure. (Voir les variables en cours d’examen)" ),
( "mcq", 1, NULL, "falls", "Falls (FAL)", "Chutes (FAL)", NULL, NULL ),
( "mcq", 2, NULL, "pain_and_discomfort", "Pain and Discomfort (HUP)", "Douleurs et malaises (HUP)", NULL, NULL ),
( "mcq", 3, NULL, "oral_health", "Oral Health (ORH)", "Santé bucco-dentaire (ORH)", NULL, NULL ),
( "mcq", 4, NULL, "snoring", "Snoring (SNO)", "Ronflement (SNO)", NULL, NULL ),
( "mcq", 5, NULL, "parkinsonism2", "Parkinsonism (PKD)", "Parkinsonisme (PKD)", NULL, NULL ),
( "mcq", 6, NULL, "health_care_utilization", "Health Care Utilization (HCU)", "Utilisation des soins de santé (HCU)", NULL, NULL ),
( "mcq", 7, NULL, "medication_use", "Medication Use (MED)", "Consommation de médicaments (MED)", NULL, NULL ),
( "mcq", 8, NULL, "dietary_supplement_use", "Dietary Supplement Use (DSU)", "Usage de suppléments alimentaires (DSU)", "Open text data for occupation and industry are available. These data are not coded. Any coding of the released open text data has to be a coordinated effort between the Approved User and the CLSA. Please contact us for details access@clsa-elcv.ca", "Des données ouvertes pour la profession et l’industrie sont disponibles. Ces données ne sont pas codées.  Toute codification de données ouvertes diffusées doit être coordonnée entre l’utilisateur autorisé et l’ÉLCV.  Pour plus d’information, contactez-nous à access@clsa-elcv.ca" ),
( "mcq", 9, NULL, "nutritional_risk", "Nutritional Risk (NUR)", "Risque nutritionnel (NUR)", NULL, NULL ),
( "mcq", 10, NULL, "physical_activities", "Physical Activities (PA2)", "Activités physiques (PA2)", NULL, NULL ),
( "mcq", 11, NULL, "psychological_distress", "Psychological Distress (K10)", "Détresse psychologique (K10)", NULL, NULL ),
( "mcq", 12, NULL, "personality_traits", "Personality Traits (PER)", "Traits de caractère (PER)", NULL, NULL ),
( "mcq", 13, NULL, "social_inequality", "Social Inequality (SEQ)", "Inégalité sociale (SEQ)", NULL, NULL ),
( "mcq", 14, NULL, "online_social_networking", "Online Social Networking (INT)", "Réseautage social en ligne (INT)", NULL, NULL ),
( "mcq", 15, NULL, "transportation_mobility_migration", "Transportation, Mobility, Migration (TRA)", "Transport, mobilité, migration (TRA)", NULL, NULL ),
( "mcq", 16, NULL, "built_environments", "Built Environments (ENV)", "Environnements construits (ENV)", NULL, NULL ),
( "mcq", 17, NULL, "wealth", "Wealth (WEA)", "Patrimoine (WEA)", NULL, NULL ),
( "physical", 1, 6, "full_questionnaire", "Full Questionnaire", "Questionnaire complet", NULL, NULL ),
( "physical", 2, 7, "weight", "Weight (WGT)", "Poids (WGT)", NULL, NULL ),
( "physical", 3, 7, "height", "Height (HGT)", "Taille (HGT)", NULL, NULL ),
( "physical", 4, 7, "body_mass_index", "Body Mass Index (HWT)", "Indice de masse corporelle (HWT)", NULL, NULL ),
( "physical", 5, NULL, "hip_and_waist_circumference", "Hip and Waist Circumference (WHC)", "Circonférence taille et hanche (WHC)", NULL, NULL ),
( "physical", 6, 8, "pulse_rate", "Pulse rate (BP)", "Fréquence du pouls (BP)", NULL, NULL ),
( "physical", 7, 8, "blood_pressure", "Blood Pressure (BP)", "Pression sanguine (BP)", NULL, NULL ),
( "physical", 8, NULL, "electrocardiogram", "Electrocardiogram (ECG)", "Électrocardiogramme (ECG)", "Raw data available through special request. For more information and for details on how to request these data, please contact access@clsa-elcv.ca", "Les données brutes sont disponibles sur demande spéciale. Pour en savoir plus sur ces données et comment en faire la demande, veuillez écrire à access@clsa-elcv.ca" ),
( "physical", 9, 9, "carotid_intima", "Carotid Intima", "Intima de la carotide", NULL, NULL ),
( "physical", 10, 9, "plaque", "Plaque", "Plaque", NULL, NULL ),
( "physical", 11, NULL, "spirometry", "Spirometry (SPR)", "Spirométrie (SPR)", "Raw data available through special request. For more information and for details on how to request these data, please contact access@clsa-elcv.ca", "Les données brutes sont disponibles sur demande spéciale. Pour en savoir plus sur ces données et comment en faire la demande, veuillez écrire à access@clsa-elcv.ca" ),
( "physical", 12, 10, "whole_body", "Whole Body", "Corps entier", NULL, NULL ),
( "physical", 13, 10, "body_parts", "Body Parts", "Parties du corps", NULL, NULL ),
( "physical", 14, 10, "dual_hip", "Dual Hip", "Deux hanches", NULL, NULL ),
( "physical", 15, 10, "forearm", "Forearm", "Avant-bras", NULL, NULL ),
( "physical", 16, 10, "iva_lateral_bone", "IVA Lateral Bone", "Os de la colonne latérale", NULL, NULL ),
( "physical", 17, 11, "body_composition_whole_body", "Body Composition (Whole Body)", "Composition corporelle (Corps entier)", NULL, NULL ),
( "physical", 18, 11, "body_composition_body_parts", "Body Composition (Body Parts)", "Composition corporelle (parties du corps)", NULL, NULL ),
( "physical", 19, 11, "aortic_calcification", "Aortic Calcification", "Calcification aortique", NULL, NULL ),
( "physical", 20, NULL, "hearing2", "Hearing (HRG)", "Audition (HRG)", NULL, NULL ),
( "physical", 21, NULL, "4_metre_walk", "4 Metre Walk (WLK)", "Marche sur 4 m (WLK)", NULL, NULL ),
( "physical", 22, NULL, "timed_get_up_and_go", "Timed Get Up and Go (TUG)", "Lever-marcher chronométré (TUG)", NULL, NULL ),
( "physical", 23, NULL, "standing_balance", "Standing Balance (BAL)", "Équilibre debout (BAL)", NULL, NULL ),
( "physical", 24, NULL, "chair_rise_balance_and_coordination", "Chair Rise: Balance and Coordination (CR)", "Se lever d’une chaise : équilibre et coordination (CR)", NULL, NULL ),
( "physical", 25, NULL, "visual_acuity", "Visual Acuity (VA)", "Acuité visuelle (VA)", NULL, NULL ),
( "physical", 26, NULL, "tonometry", "Tonometry (TON)", "Tonométrie (TON)", "Raw data available through special request. For more information and for details on how to request these data, please contact access@clsa-elcv.ca", "Les données brutes sont disponibles sur demande spéciale. Pour en savoir plus sur ces données et comment en faire la demande, veuillez écrire à access@clsa-elcv.ca" ),
( "physical", 27, NULL, "retinal_scan", "Retinal Scan (RS)", "Scan de la rétine (RS)", NULL, NULL ),
( "physical", 28, NULL, "grip_strength", "Grip Strength (GS)", "Force de préhension (GS)", NULL, NULL ),
( "biomarker", 1, NULL, "white_blood_cells", "White blood cells", "Globules blancs", NULL, NULL ),
( "biomarker", 2, NULL, "lymphocytes_relative_number", "Lymphocytes (relative number)", "Lymphocytes (nombre relatif)", NULL, NULL ),
( "biomarker", 3, NULL, "monocytes_relative_number", "Monocytes (relative number)", "Monocytes (nombre relatif)", NULL, NULL ),
( "biomarker", 4, NULL, "granulocytes_relative_number", "Granulocytes (relative number)", "Granulocytes (nombre relatif)", NULL, NULL ),
( "biomarker", 5, NULL, "lymphocytes_absolute_number", "Lymphocytes (absolute number)", "Lymphocytes (nombre absolu)", NULL, NULL ),
( "biomarker", 6, NULL, "monocytes_absolute_number", "Monocytes (absolute number)", "Monocytes (nombre absolu)", NULL, NULL ),
( "biomarker", 7, NULL, "granulocytes_absolute_number", "Granulocytes (absolute number)", "Granulocytes (nombre absolu)", NULL, NULL ),
( "biomarker", 8, NULL, "red_blood_cells", "Red blood cells", "Globules rouges", NULL, NULL ),
( "biomarker", 9, NULL, "hemoglobin", "Hemoglobin", "Hémoglobine", NULL, NULL ),
( "biomarker", 10, NULL, "hematocrit", "Hematocrit", "Hématocrites", NULL, NULL ),
( "biomarker", 11, NULL, "mean_corpuscular_volume", "Mean corpuscular volume", "Volume globulaire moyen", NULL, NULL ),
( "biomarker", 12, NULL, "mean_corpuscular_hemoglobin", "Mean corpuscular hemoglobin", "Teneur corpusculaire moyenne en hémoglobine", NULL, NULL ),
( "biomarker", 13, NULL, "mean_corpuscular_hemoglobin_concentration", "Mean corpuscular hemoglobin concentration", "Concentration corpusculaire moyenne en hémoglobine", NULL, NULL ),
( "biomarker", 14, NULL, "red_blood_cell_distribution_width", "Red blood cell distribution width", "Variation de la grosseure des globules rouges", NULL, NULL ),
( "biomarker", 15, NULL, "platelets", "Platelets", "Plaquettes", NULL, NULL ),
( "biomarker", 16, NULL, "mean_platelet_volume", "Mean platelet volume", "Volume plaquettaire moyen", NULL, NULL );
