SELECT "Creating new qnaire table" AS "";

CREATE TABLE IF NOT EXISTS qnaire (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL,
  create_timestamp TIMESTAMP NOT NULL,
  qnaire_type_id INT UNSIGNED NOT NULL,
  cohort ENUM('comprehensive', 'tracking') NOT NULL,
  replacement VARCHAR(45) NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX uq_qnaire_type_id_cohort (qnaire_type_id ASC, cohort ASC),
  INDEX fk_qnaire_type_id (qnaire_type_id ASC),
  CONSTRAINT fk_qnaire_qnaire_type_id
    FOREIGN KEY (qnaire_type_id)
    REFERENCES qnaire_type (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT IGNORE INTO qnaire( qnaire_type_id, cohort, replacement ) VALUES
( 1, 'tracking', NULL ),
( 1, 'comprehensive', NULL ),
( 2, 'tracking', NULL ),
( 2, 'comprehensive', NULL ),
( 3, 'tracking', NULL ),
( 3, 'comprehensive', NULL ),
( 4, 'tracking', NULL ),
( 4, 'comprehensive', NULL ),
( 5, 'tracking', NULL ),
( 5, 'comprehensive', NULL ),
( 6, 'tracking', NULL ),
( 6, 'comprehensive', NULL ),
( 7, 'tracking', NULL ),
( 7, 'comprehensive', NULL ),
( 8, 'tracking', NULL ),
( 8, 'comprehensive', NULL ),
( 9, 'tracking', NULL ),
( 9, 'comprehensive', NULL ),
( 10, 'tracking', NULL ),
( 10, 'comprehensive', NULL ),
( 11, 'tracking', NULL ),
( 11, 'comprehensive', NULL ),
( 12, 'tracking', NULL ),
( 12, 'comprehensive', NULL ),
( 13, 'tracking', NULL ),
( 13, 'comprehensive', NULL ),
( 14, 'tracking', NULL ),
( 14, 'comprehensive', NULL ),
( 15, 'tracking', NULL ),
( 15, 'comprehensive', 'See Physical Assessments (WGT, HGT)' ),
( 16, 'tracking', NULL ),
( 16, 'comprehensive', NULL ),
( 17, 'tracking', NULL ),
( 17, 'comprehensive', NULL ),
( 18, 'tracking', NULL ),
( 18, 'comprehensive', NULL ),
( 19, 'tracking', NULL ),
( 19, 'comprehensive', NULL ),
( 20, 'tracking', 'Not applicable' ),
( 20, 'comprehensive', NULL ),
( 21, 'tracking', NULL ),
( 21, 'comprehensive', NULL ),
( 22, 'tracking', NULL ),
( 22, 'comprehensive', NULL ),
( 23, 'tracking', NULL ),
( 23, 'comprehensive', NULL );
