SELECT "Creating new service table" AS "";

CREATE TABLE IF NOT EXISTS service(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL,
  create_timestamp TIMESTAMP NOT NULL,
  method ENUM('DELETE','GET','PATCH','POST','PUT') NOT NULL,
  subject VARCHAR(45) NOT NULL,
  resource TINYINT(1) NOT NULL DEFAULT 0,
  restricted TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE INDEX uq_method_subject_resource (method ASC, subject ASC, resource ASC))
ENGINE = InnoDB;

-- rebuild the service list
DELETE FROM service;
ALTER TABLE service AUTO_INCREMENT = 1;
INSERT INTO service ( subject, method, resource, restricted ) VALUES

-- framework services
( 'access', 'DELETE', 1, 1 ),
( 'access', 'GET', 0, 1 ),
( 'access', 'POST', 0, 1 ),
( 'activity', 'GET', 0, 1 ),
( 'application', 'GET', 0, 1 ),
( 'application', 'GET', 1, 0 ),
( 'application', 'PATCH', 1, 1 ),
( 'application_type', 'GET', 0, 0 ),
( 'application_type', 'GET', 1, 0 ),
( 'cohort', 'GET', 0, 0 ),
( 'failed_login', 'GET', 0, 1 ),
( 'language', 'GET', 0, 0 ),
( 'language', 'GET', 1, 0 ),
( 'overview', 'GET', 0, 0 ),
( 'overview', 'GET', 1, 0 ),
( 'report', 'DELETE', 1, 1 ),
( 'report', 'GET', 0, 1 ),
( 'report', 'GET', 1, 1 ),
( 'report', 'PATCH', 1, 1 ),
( 'report', 'POST', 0, 1 ),
( 'report_restriction', 'DELETE', 1, 1 ),
( 'report_restriction', 'GET', 0, 1 ),
( 'report_restriction', 'GET', 1, 1 ),
( 'report_restriction', 'PATCH', 1, 1 ),
( 'report_restriction', 'POST', 0, 1 ),
( 'report_schedule', 'DELETE', 1, 1 ),
( 'report_schedule', 'GET', 0, 1 ),
( 'report_schedule', 'GET', 1, 1 ),
( 'report_schedule', 'PATCH', 1, 1 ),
( 'report_schedule', 'POST', 0, 1 ),
( 'report_type', 'GET', 0, 1 ),
( 'report_type', 'GET', 1, 1 ),
( 'report_type', 'PATCH', 1, 1 ),
( 'role', 'GET', 0, 0 ),
( 'self', 'DELETE', 1, 0 ),
( 'self', 'GET', 1, 0 ),
( 'self', 'PATCH', 1, 0 ),
( 'self', 'POST', 1, 0 ),
( 'setting', 'GET', 0, 1 ),
( 'setting', 'GET', 1, 0 ),
( 'setting', 'PATCH', 1, 1 ),
( 'site', 'DELETE', 1, 1 ),
( 'site', 'GET', 0, 0 ),
( 'site', 'GET', 1, 1 ),
( 'site', 'PATCH', 1, 1 ),
( 'site', 'POST', 0, 1 ),
( 'system_message', 'DELETE', 1, 1 ),
( 'system_message', 'GET', 0, 0 ),
( 'system_message', 'GET', 1, 1 ),
( 'system_message', 'PATCH', 1, 1 ),
( 'system_message', 'POST', 0, 1 ),
( 'user', 'DELETE', 1, 1 ),
( 'user', 'GET', 0, 0 ),
( 'user', 'GET', 1, 0 ),
( 'user', 'PATCH', 1, 1 ),
( 'user', 'POST', 0, 1 ),

-- application services
( 'data_option', 'GET', 0, 0 ),
( 'data_option', 'GET', 1, 0 ),
( 'data_option_subcategory', 'GET', 0, 0 ),
( 'data_option_subcategory', 'GET', 1, 0 ),
( 'data_option_parent', 'GET', 0, 0 ),
( 'data_option_parent', 'GET', 1, 0 ),
( 'coapplicant', 'DELETE', 1, 1 ),
( 'coapplicant', 'GET', 0, 0 ),
( 'coapplicant', 'GET', 1, 0 ),
( 'coapplicant', 'POST', 0, 1 ),
( 'deadline', 'DELETE', 1, 1 ),
( 'deadline', 'GET', 0, 1 ),
( 'deadline', 'GET', 1, 1 ),
( 'deadline', 'PATCH', 1, 1 ),
( 'deadline', 'POST', 0, 1 ),
( 'dsac_review', 'GET', 0, 1 ),
( 'dsac_review', 'GET', 1, 1 ),
( 'dsac_review', 'PATCH', 1, 1 ),
( 'notification', 'GET', 0, 1 ),
( 'notification_type', 'GET', 0, 1 ),
( 'notification_type', 'GET', 1, 1 ),
( 'pdf_form', 'GET', 0, 1 ),
( 'pdf_form', 'GET', 1, 1 ),
( 'pdf_form_type', 'GET', 0, 1 ),
( 'pdf_form_type', 'GET', 1, 1 ),
( 'pdf_form_type', 'PATCH', 1, 1 ),
( 'progress_report', 'DELETE', 1, 1 ),
( 'progress_report', 'GET', 0, 0 ),
( 'progress_report', 'GET', 1, 0 ),
( 'progress_report', 'PATCH', 1, 1 ),
( 'progress_report', 'POST', 0, 1 ),
( 'production', 'DELETE', 1, 1 ),
( 'production', 'GET', 0, 0 ),
( 'production', 'GET', 1, 0 ),
( 'production', 'PATCH', 1, 1 ),
( 'production', 'POST', 0, 1 ),
( 'production_type', 'GET', 0, 0 ),
( 'production_type', 'GET', 1, 0 ),
( 'reference', 'DELETE', 1, 1 ),
( 'reference', 'GET', 0, 0 ),
( 'reference', 'GET', 1, 0 ),
( 'reference', 'PATCH', 1, 1 ),
( 'reference', 'POST', 0, 1 ),
( 'reqn', 'DELETE', 1, 1 ),
( 'reqn', 'GET', 0, 0 ),
( 'reqn', 'GET', 1, 0 ),
( 'reqn', 'PATCH', 1, 1 ),
( 'reqn', 'POST', 0, 1 ),
( 'reqn_note', 'GET', 0, 0 ),
( 'reqn_note', 'GET', 1, 0 ),
( 'reqn_note', 'PATCH', 1, 1 ),
( 'reqn_note', 'POST', 0, 1 ),
( 'review', 'GET', 0, 1 ),
( 'review', 'GET', 1, 1 ),
( 'review', 'PATCH', 1, 1 ),
( 'stage', 'GET', 0, 1 ),
( 'stage_type', 'GET', 0, 1 ),
( 'stage_type', 'GET', 1, 1 );
