CREATE TABLE data_category (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  rank INT(10) UNSIGNED NOT NULL,
  comment TINYINT(1) NOT NULL DEFAULT 0,
  name_en VARCHAR(127) NOT NULL,
  name_fr VARCHAR(127) NOT NULL,
  condition_en TEXT NULL DEFAULT NULL,
  condition_fr TEXT NULL DEFAULT NULL,
  note_en TEXT NULL DEFAULT NULL,
  note_fr TEXT NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX uq_rank (rank ASC),
  UNIQUE INDEX uq_name_en (name_en ASC),
  UNIQUE INDEX uq_name_fr (name_fr ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
