CREATE TABLE output_source (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  output_id INT(10) UNSIGNED NOT NULL,
  filename VARCHAR(255) NULL DEFAULT NULL,
  data LONGTEXT NULL DEFAULT NULL,
  url VARCHAR(1023) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX fk_output_id (output_id ASC),
  CONSTRAINT fk_output_source_output_id
    FOREIGN KEY (output_id)
    REFERENCES magnolia.output (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
